# 异常

> 原文：<https://www.learn-php.org/en/Exceptions>

* * *

PHP 有一个类似于其他编程语言的异常模型。在 PHP 中可以抛出和捕获异常。代码可以放在 try 块中，以便于捕捉潜在的异常。每个 try 必须至少有一个相应的 catch 或 finally 块。

```php
try {
  echo 2 / 0;
} catch (Exception $e) {
  echo "Caught exception: Division by zero!";
} 
```

可以使用多个 catch 块来捕获不同类别的异常。正常执行(当 try 块中没有抛出异常时)将在序列中定义的最后一个 catch 块之后继续。异常可以在 catch 块中抛出(或再次抛出)。

```php
if (4/2 == 2) {
  echo "Right!";
} else {
  throw new Exception("Wrong answer!");
} 
```

当抛出异常时，语句后面的代码将不会被执行，PHP 将试图找到第一个匹配的 catch 块。如果一个异常没有被捕获，一个 PHP 致命错误将会以“未被捕获的异常...”发出消息，除非已经用 set_exception_handler()定义了处理程序。

## 最终阻止

在 PHP 5.5 和更高版本中，finally 块也可以在 catch 块之后或代替 catch 块指定。finally 块中的代码将总是在 try 和 catch 块之后执行,而不管是否抛出了异常，并且在正常执行恢复之前执行。

```php
try {
  echo 4/0;
} catch (Exception $e) {
  echo "Divided by zero!";
} finally {
  echo "This will be outputed even if exception will happen!";
} 
```

## 练习

使用 try-catch-finally 块首先捕获异常并打印出`Exception caught!`，然后最终打印出`Done!`。您的最终输出应该类似于:`Exception caught! Done!`